sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SRhZitaFbfACQiS+vuZg7yEQcaJJtqgKrfGiDAV06dt+BFnwbrENYuQBVeuub7WWB5qs6PfYhJbBaqVtj76bn2CJa8Hev4aHtOiqBgvXaoBIo2QRhu+O0o5chRXinEHVnsUOqvPc6CCvHFt+sHKfAj8dFG+P958c3/QROU32db3VC7H4JX+OVSoytF25L/P3ifUB0CT5JAdeRLEQRsxRfOcGuR3ROb6MyP77SAwxPbTwAYHe3cegFXmDGhKGs3gEk0I1d3OFLzN+UVTHAXAb6lC6XdlBD2NIaF+fzndpTqIbYpK77QaWCqvZDBrBZTIRT7nO/1RawvVYhLz8udUqV5TYxt8FVAjLQ1G8O/9GGYM6CDYEzvz53nZ3JJd4xjSRPsf0CX6x2oiPcGeWtT3FZWuj6NokKewm+CcXa3//RoWB08c0bFzLr5mG3OAtRLd0cl3jEWvTatAhN1guMYUSZ44hi2+nEiE+lVb7JwWle6CjoxaZMosLOzJM/G780vSeKb+OP/7zFNnmrOtlS3KQb9hxZzmPIjpYMnOqvdb/K17g/wS8L25VuIYH1d1TDn/MdKxdlIJpcgclv+QFF/fzYbCDkGNiwHpsd3W5ZFxRye9iz1hrTHpa7uzFiK25DIi3w/d/oNG1XhCZ/IGcJ+kaQSFF/Zig0jRlW3IMXIapU7E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/An-Exhortation-to-Peace-and-Unity_3614
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy